name: Build and release DVI LV Heatpump Card

on:
  push:
    tags:
      - "v*"

jobs:
  build-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Build the dist folder for HACS
      - name: Prepare dist folder
        run: |
          rm -rf dist
          mkdir -p dist/dvi-lv
          cp sidecar/www/dvi-card/dvi-lv-heatpump-card.js dist/
          cp -r sidecar/www/dvi-card/dvi-lv/* dist/dvi-lv/    